### ISSUE TITLE
URLs prefix issue

### ISSUE THREAD

**Issue by elv0816** [iMakedonsky/drf-autodocs#6]
For example:

```
tasks_urlpatterns = [
    url(r'^$', views.TaskList.as_view(), name='list'),
    url(r'^/create$', views.TaskCreate.as_view(), name='create'),
]

urlpatterns = [
    url(r'^tasks', include(tasks_urlpatterns), name='tasks'),
]
```

In this case, the URLs should be:
tasks-list: /tasks
tasks-create: /tasks/create

However, it generates:
tasks-list: /tasks/
tasks-create: /tasks/create

Very nice DRF extension, love it. Hope this can be fixed. Cheers.

**Comment by iMakedonsky** [comment]
Thanks, gonna fix this in next release.

**Comment by iMakedonsky** [comment]
Checked the issue and reproduced it. Creating such urlpatterns, that have no trailing slash but have childs with leading slash is deprecated by django itself and produces warnings, so sorry, but this won't be changed.
